
server:
  port: 8888
spring:
  application:
    name: remoteconfig-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:share
  profiles:
    active: native  #服务器资源来自本地
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/alex-ge123/j2003_alex_finallyproject.git #配置文件资源库
#          search-paths:  remoteconfig-file  #在资源库的搜索路径
  rabbitmq:
    host: 10.12.153.77
    virtual-host: /
    port: 5672
    username: leen
    password: 123456
eureka:
  client:
    service-url:
      defaultZone:  http://root:root@10.12.153.77:8761/eureka/, http://root:root@10.12.153.77:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
