
server:
  port: 8888
spring:
  application:
    name: remoteconfig-service123
  cloud:
    config:
      server:
        git:
          search-paths: remoteconfig-file  #在资源库的搜索路径

          uri: https://github.com/alex-ge123/j2003_alex_finallyproject.git  #配置文件资源库
  rabbitmq:
    virtual-host: /
    port: 5672
    username: guest
    password: guest
    host: localhost

eureka:
  client:
    service-url:
      defaultZone:  http://root:root@10.12.153.63:8761/eureka/, http://root:root@10.12.153.63:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"