spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.12.153.77:3306/education?serverTimezone=UTC
    username: root
    password: ROOT
  # 应用名称
  #spring.application.name=j2003_alex_coursemanagement
  # 数据库驱动：
  #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  # 数据源名称
  #spring.datasource.name=defaultDataSource
  # 数据库连接地址
  #spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
  # 数据库用户名&密码：
  #spring.datasource.username=***
  #spring.datasource.password=***
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.j2003.pojo
server:
  port: 10003
