spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/, http://root:root@localhost:8762/eureka/
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    lg:
      path: /lg/**
      serviceId: login-service
  sensitive-headers:


