spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      #defaultZone: http://root:root@10.12.153.77:8761/eureka/, http://root:root@10.12.153.77:8762/eureka/
      defaultZone: http://root:root@localhost:8761/eureka/, http://root:root@localhost:8762/eureka/
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
#自定义路由
zuul:
  routes:
    alex:
      path: /alex/**
      serviceId:
    ignored-services: alex-prodcuer-coursemanagement,alex-prodcuer-coursemanagement2
